fix an error when centos linux system without install X-server
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.XplatUI' threw an exception. ---> System.ArgumentNullException: Could not open display (X-Server required. Check your DISPLAY environment variable)
Parameter name: Display
  at System.Windows.Forms.XplatUIX11.SetDisplay (System.IntPtr display_handle) [0x00408] in <01b7792664764a0a8aecd9a1e8220761>:0
  at System.Windows.Forms.XplatUIX11..ctor () [0x00077] in <01b7792664764a0a8aecd9a1e8220761>:0
  at System.Windows.Forms.XplatUIX11.GetInstance () [0x00019] in <01b7792664764a0a8aecd9a1e8220761>:0
  at System.Windows.Forms.XplatUI..cctor () [0x000c0] in <01b7792664764a0a8aecd9a1e8220761>:0
   --- End of inner exception stack trace ---
  at System.Windows.Forms.Application.DoEvents () [0x00000] in <01b7792664764a0a8aecd9a1e8220761>:0
  at Microsoft.VisualBasic.Data.ChartPlots.Scatter.Plot (System.Collections.Generic.IEnumerable`1[T] c, Microsoft.VisualBasic.Imaging.IGraphics g, Microsoft.VisualBasic.Imaging.Drawing2D.GraphicsRegion rect, System.String bg, System.Boolean showGrid, System.Boolean showLegend, System.Drawing.Point legendPosition, System.String legendSize, System.Boolean drawLine, Microsoft.VisualBasic.MIME.Markup.HTML.CSS.Stroke legendBorder, Microsoft.VisualBasic.MIME.Markup.HTML.CSS.Stroke legendRegionBorder, System.Boolean fill, System.Boolean fillPie, System.String legendFontCSS, System.Boolean absoluteScaling, System.Boolean XaxisAbsoluteScalling, System.Boolean YaxisAbsoluteScalling, System.Boolean drawAxis, System.String Xlabel, System.String Ylabel, System.String yaxis, System.String xaxis, Microsoft.VisualBasic.Imaging.Drawing2D.Shapes.Line[] ablines, System.Boolean htmlLabel, System.Double ticksY, System.Boolean preferPositive, Microsoft.VisualBasic.Math.Interpolation.Splines interplot, System.Boolean densityColor, System.String tickFontStyle, System.String labelFontStyle, System.String title, System.String titleFontCSS, Microsoft.VisualBasic.Data.ChartPlots.Graphic.Axis.XAxisLayoutStyles xlayout, Microsoft.VisualBasic.Data.ChartPlots.Graphic.Axis.YAxisLayoutStyles ylayout, System.String gridFill, System.String gridColor, System.String legendBgFill, System.Int32 legendSplit, System.String[] hullConvexList, System.String XtickFormat, System.String YtickFormat, System.String axisStroke, System.Boolean scatterReorder) [0x0063a] in <c2c4c2e208a641f2902510dc896c6266>:0
  at SMRUCC.genomics.Visualize.ExpressionPattern.PatternPlot.PlotInternal (Microsoft.VisualBasic.Imaging.IGraphics& g, Microsoft.VisualBasic.Imaging.Drawing2D.GraphicsRegion canvas) [0x00377] in <a48494eb8d294b33bb67fa54bdd768b1>:0
  at Microsoft.VisualBasic.Imaging.Drawing2D.g.GraphicsPlots (System.Drawing.Size& size, Microsoft.VisualBasic.MIME.Markup.HTML.CSS.Padding& padding, System.String bg, Microsoft.VisualBasic.Imaging.Drawing2D.IPlot plotAPI, Microsoft.VisualBasic.Imaging.Driver.Drivers driver, System.String dpi) [0x001a1] in <2af6430e2b254948b09fb75697f4f886>:0
  at Microsoft.VisualBasic.Data.ChartPlots.Graphic.Plot.Plot (System.String size, System.Int32 ppi, Microsoft.VisualBasic.Imaging.Driver.Drivers driver) [0x0004e] in <c2c4c2e208a641f2902510dc896c6266>:0
  at SMRUCC.genomics.Visualize.ExpressionPattern.PatternPlotExtensions.DrawMatrix (SMRUCC.genomics.Visualize.ExpressionPattern.ExpressionPattern matrix, System.String size, System.String padding, System.String bg, System.String title, System.String xlab, System.String ylab, System.String colorSet, System.Int32 levels) [0x00054] in <a48494eb8d294b33bb67fa54bdd768b1>:0
  at visualkit.visualPlot.PlotExpressionPatterns (SMRUCC.genomics.Visualize.ExpressionPattern.ExpressionPattern matrix, System.Object size, System.Object padding, System.Object bg, System.String colorSet, System.Int32 levels) [0x00032] in <d71cb2ac5bec43f38d6784876dc5fc1d>:0
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <d50a1f2f14b642d2b936cb144b307343>:0
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <d50a1f2f14b642d2b936cb144b307343>:0
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <d50a1f2f14b642d2b936cb144b307343>:0
  at SMRUCC.Rsharp.Runtime.Interop.RMethodInfo.Invoke (System.Object[] parameters, SMRUCC.Rsharp.Runtime.Environment env) [0x0009c] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Runtime.Interop.RMethodInfo.Invoke (SMRUCC.Rsharp.Runtime.Environment envir, SMRUCC.Rsharp.Runtime.Components.InvokeParameter[] params) [0x00199] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.ExecuteEngine.ExpressionSymbols.Closure.FunctionInvoke.doInvokeFuncVar (SMRUCC.Rsharp.Runtime.Components.Interface.RFunction funcVar, SMRUCC.Rsharp.Runtime.Environment envir) [0x000ca] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.ExecuteEngine.ExpressionSymbols.Closure.FunctionInvoke.Evaluate (SMRUCC.Rsharp.Runtime.Environment envir) [0x0007b] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.ExecuteEngine.ExpressionSymbols.Operators.ValueAssign.Evaluate (SMRUCC.Rsharp.Runtime.Environment envir) [0x00009] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.ExecutableLoop.ExecuteCodeLine (SMRUCC.Rsharp.Interpreter.ExecuteEngine.Expression expression, SMRUCC.Rsharp.Runtime.Environment envir, System.Boolean& breakLoop, System.Boolean debug) [0x0001c] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.ExecutableLoop.Execute (System.Collections.Generic.IEnumerable`1[T] execQueue, SMRUCC.Rsharp.Runtime.Environment env) [0x00024] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.RInterpreter.RunInternal (SMRUCC.Rsharp.Runtime.Components.Rscript Rscript, Microsoft.VisualBasic.ComponentModel.DataSourceModel.NamedValue`1[System.Object][] arguments) [0x0003e] in <df5a19344a9543a89524695066bf337e>:0
  at SMRUCC.Rsharp.Interpreter.RInterpreter.Source (System.String filepath, Microsoft.VisualBasic.ComponentModel.DataSourceModel.NamedValue`1[System.Object][] arguments) [0x00039] in <df5a19344a9543a89524695066bf337e>:0
  at Rterm.Program.RunScript (System.String filepath, Microsoft.VisualBasic.CommandLine.CommandLine args) [0x000b7] in <9955460dc22c49c0a94fd0b388755593>:0
  at Microsoft.VisualBasic.CommandLine.Interpreter.apiInvokeEtc (System.String commandName, Microsoft.VisualBasic.CommandLine.CommandLine cli) [0x00041] in <62aa20b9b157474d8f2bf9b6bde71758>:0
  at Microsoft.VisualBasic.CommandLine.Interpreter.apiInvoke (System.String commandName, System.Object[] args, System.String[] help_argvs) [0x0023d] in <62aa20b9b157474d8f2bf9b6bde71758>:0
  at Microsoft.VisualBasic.CommandLine.Interpreter.Execute (Microsoft.VisualBasic.CommandLine.CommandLine args) [0x00025] in <62aa20b9b157474d8f2bf9b6bde71758>:0
  at Microsoft.VisualBasic.App.RunCLIInternal (System.Type App, Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller, Microsoft.VisualBasic.CommandLine.ExecuteEmptyCLI executeEmpty, Microsoft.VisualBasic.CommandLine.ExecuteNotFound executeNotFound, Microsoft.VisualBasic.CommandLine.ExecuteFile executeFile) [0x00055] in <62aa20b9b157474d8f2bf9b6bde71758>:0
  at Rterm.Program.Main () [0x00010] in <9955460dc22c49c0a94fd0b388755593>:0