try to fix the bugs of missing assembly on linux platform
Unhandled Exception:
System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <47d423fd1d4342b9832b2fe1f5d431eb>:0
  at Microsoft.VisualBasic.My.FrameworkInternal.Config.fetchConfig (Microsoft.VisualBasic.My.FrameworkInternal.Config config, System.String file) [0x00008] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.My.FrameworkInternal.Config.saveDefault () [0x00067] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.My.FrameworkInternal.Config.Load () [0x00013] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.ApplicationServices.Debugging.DebuggerArgs.InitDebuggerEnvir (Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller) [0x0008f] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.App.RunCLIInternal (System.Type App, Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller, Microsoft.VisualBasic.CommandLine.ExecuteEmptyCLI executeEmpty, Microsoft.VisualBasic.CommandLine.ExecuteNotFound executeNotFound, Microsoft.VisualBasic.CommandLine.ExecuteFile executeFile) [0x00001] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.App.RunCLI (System.Type Interpreter, Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller) [0x00001] in <117d975309e9486d8f8363f02be5ff76>:0
  at Rserve.Program.Main () [0x00010] in <d95486c11efa4fd69dfe689c0e365326>:0
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <47d423fd1d4342b9832b2fe1f5d431eb>:0
  at Microsoft.VisualBasic.My.FrameworkInternal.Config.fetchConfig (Microsoft.VisualBasic.My.FrameworkInternal.Config config, System.String file) [0x00008] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.My.FrameworkInternal.Config.saveDefault () [0x00067] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.My.FrameworkInternal.Config.Load () [0x00013] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.ApplicationServices.Debugging.DebuggerArgs.InitDebuggerEnvir (Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller) [0x0008f] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.App.RunCLIInternal (System.Type App, Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller, Microsoft.VisualBasic.CommandLine.ExecuteEmptyCLI executeEmpty, Microsoft.VisualBasic.CommandLine.ExecuteNotFound executeNotFound, Microsoft.VisualBasic.CommandLine.ExecuteFile executeFile) [0x00001] in <117d975309e9486d8f8363f02be5ff76>:0
  at Microsoft.VisualBasic.App.RunCLI (System.Type Interpreter, Microsoft.VisualBasic.CommandLine.CommandLine args, System.String caller) [0x00001] in <117d975309e9486d8f8363f02be5ff76>:0
  at Rserve.Program.Main () [0x00010] in <d95486c11efa4fd69dfe689c0e365326>:0
System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'